### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by linyiyi1314** [Nyan-Work/oh-my-minecraft-client#12]
### Question Type

Codes

### Description

用了最新版1.20ommc
启动游戏一直进不去
1.20版本和通用版本我都试过了

**Comment by Hendrix-Shen** [comment]
请上传日志信息。

**Comment by linyiyi1314** [comment]
> 请上传日志信息。

没有日志 单纯的卡在启动界面 删了ommc就可以进去

**Comment by Hendrix-Shen** [comment]
上传你的latest.log

**Comment by linyiyi1314** [comment]
log是啥 这个mod吗

**Comment by Hendrix-Shen** [comment]
在.minecraft/logs/latest.log

**Comment by linyiyi1314** [comment]
[Uploading 2023-07-05-7.log.gz…]()

**Comment by Hendrix-Shen** [comment]
你把文件内容复制下来发到这吧，你“上传”的文件没法下载。

**Comment by linyiyi1314** [comment]
```
[17:27:55] [main/INFO]: Loading Minecraft 1.20 with Fabric Loader 0.14.21
[17:27:55] [main/INFO]: Loading 139 mods:
	- advancementinfo 1.20-fabric0.83.0-1.4
	- appleskin 2.5.0+mc1.20
	- architectury 9.0.8
	- armorchroma 1.2.6
	- betterf3 7.0.0
	- carpet 1.4.112+v230608
	- cloth-config 11.0.99
	   \-- cloth-basic-math 0.6.1
	- continuity 3.0.0-beta.2+1.20
	- controlling 12.0.2
	- customskinloader 14.16
	- dynamicfps 2.4.0
	   \-- com_moandjiezana_toml_toml4j 0.7.2
	- enhancedblockentities 0.8.1+1.20.1
	   |-- advanced_runtime_resource_pack 0.6.7
	   \-- spruceui 5.0.0+1.20
	- fabric-api 0.83.0+1.20
	   |-- fabric-api-base 0.4.29+b04edc7a27
	   |-- fabric-api-lookup-api-v1 1.6.34+4d8536c927
	   |-- fabric-biome-api-v1 13.0.10+b3afc78b27
	   |-- fabric-block-api-v1 1.0.9+e022e5d127
	   |-- fabric-blockrenderlayer-v1 1.1.39+b3afc78b27
	   |-- fabric-client-tags-api-v1 1.0.20+b3afc78b27
	   |-- fabric-command-api-v1 1.2.32+f71b366f27
	   |-- fabric-command-api-v2 2.2.11+b3afc78b27
	   |-- fabric-commands-v0 0.2.49+df3654b327
	   |-- fabric-containers-v0 0.1.61+df3654b327
	   |-- fabric-content-registries-v0 4.0.7+b3afc78b27
	   |-- fabric-convention-tags-v1 1.5.3+b3afc78b27
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe27
	   |-- fabric-data-generation-api-v1 12.1.10+b3afc78b27
	   |-- fabric-dimensions-v1 2.1.51+b3afc78b27
	   |-- fabric-entity-events-v1 1.5.21+b3afc78b27
	   |-- fabric-events-interaction-v0 0.6.0+b3afc78b27
	   |-- fabric-events-lifecycle-v0 0.2.61+df3654b327
	   |-- fabric-game-rule-api-v1 1.0.38+b04edc7a27
	   |-- fabric-item-api-v1 2.1.26+b3afc78b27
	   |-- fabric-item-group-api-v1 4.0.7+b3afc78b27
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da27
	   |-- fabric-keybindings-v0 0.2.34+df3654b327
	   |-- fabric-lifecycle-events-v1 2.2.20+b3afc78b27
	   |-- fabric-loot-api-v2 1.1.37+b3afc78b27
	   |-- fabric-loot-tables-v1 1.1.41+9e7660c627
	   |-- fabric-message-api-v1 5.1.6+b3afc78b27
	   |-- fabric-mining-level-api-v1 2.1.47+b3afc78b27
	   |-- fabric-models-v0 0.3.35+b3afc78b27
	   |-- fabric-networking-api-v1 1.3.8+b3afc78b27
	   |-- fabric-networking-v0 0.3.48+df3654b327
	   |-- fabric-object-builder-api-v1 11.0.6+b3afc78b27
	   |-- fabric-particles-v1 1.0.28+b3afc78b27
	   |-- fabric-recipe-api-v1 1.0.18+b3afc78b27
	   |-- fabric-registry-sync-v0 2.2.6+b3afc78b27
	   |-- fabric-renderer-api-v1 3.0.1+b3afc78b27
	   |-- fabric-renderer-indigo 1.3.1+b3afc78b27
	   |-- fabric-renderer-registries-v1 3.2.44+df3654b327
	   |-- fabric-rendering-data-attachment-v1 0.3.33+b3afc78b27
	   |-- fabric-rendering-fluids-v1 3.0.26+b3afc78b27
	   |-- fabric-rendering-v0 1.1.47+df3654b327
	   |-- fabric-rendering-v1 3.0.6+b3afc78b27
	   |-- fabric-resource-conditions-api-v1 2.3.4+b3afc78b27
	   |-- fabric-resource-loader-v0 0.11.7+f7923f6d27
	   |-- fabric-screen-api-v1 2.0.6+b3afc78b27
	   |-- fabric-screen-handler-api-v1 1.3.27+b3afc78b27
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b27
	   |-- fabric-transfer-api-v1 3.2.2+b3afc78b27
	   \-- fabric-transitive-access-wideners-v1 4.2.0+b3afc78b27
	- fabric-language-kotlin 1.9.6+kotlin.1.8.22
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.8.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.8.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.22
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.21.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.1
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.1
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.1
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.1
	- fabricloader 0.14.21
	- fastchest 1.4+1.20
	- gca 2.6.0-1.20
	- i18nupdatemod 3.5.0
	- imblocker 4.0.0-alpha20230701
	- immediatelyfast 1.1.15+1.20.1
	   |-- com_github_llamalad7_mixinextras 0.2.0-beta.8
	   \-- net_lenni0451_reflect 1.1.0
	- indium 1.0.18+mc1.20
	- inventoryhud 3.4.13
	- inventoryprofilesnext 1.10.6
	- iris 1.6.4
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- jade 11.1.4
	- java 18
	- libipn 3.0.2
	- litematica 0.15.0
	- lithium 0.11.2
	- magiclib 0.7.346+e235d92-stable
	   \-- magiclib-1_20_1 0.7.346+e235d92-stable
	- malilib 0.16.0
	- masa_gadget_mod 3.2.309+75a7dc7-stable
	   \-- masa_gadget_mod-1_20_1 3.2.309+75a7dc7-stable
	- minecraft 1.20
	- minecraftcapes 12.3.5
	- minihud 0.27.0
	- modmenu 7.0.1
	   |-- fabric-api-base 0.4.29+b04edc7a27
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da27
	   |-- fabric-lifecycle-events-v1 2.2.20+b3afc78b27
	   |-- fabric-resource-loader-v0 0.11.7+f7923f6d27
	   \-- fabric-screen-api-v1 2.0.6+b3afc78b27
	- moreculling 1.20-0.18.1
	   |-- com_github_llamalad7_mixinextras 0.2.0-beta.8
	   \-- conditional-mixin 0.3.2
	- mousetweaks 2.25
	- ommc 0.5.294+e12a73f-beta
	   \-- ommc-1_20_1 0.5.294+e12a73f-beta
	- quickshulker 1.4.0-1.20
	   |-- kyrptconfig 1.5.4-1.20
	   \-- shulkerutils 1.0.4-1.19
	- reeses-sodium-options 1.5.1+mc1.20-build.74
	- roughlyenoughitems 12.0.626
	   \-- error_notifier 1.0.9
	- searchables 1.0.2
	- sodium 0.4.10+build.27
	   |-- fabric-api-base 0.4.29+b04edc7a27
	   |-- fabric-rendering-data-attachment-v1 0.3.33+b3afc78b27
	   |-- fabric-rendering-fluids-v1 3.0.26+b3afc78b27
	   \-- fabric-resource-loader-v0 0.11.7+f7923f6d27
	- sodium-extra 0.4.20+mc1.20-build.103
	   |-- caffeineconfig 1.1.0+1.17
	   \-- crowdin-translate 1.4+1.19.3
	- starlight 1.1.2+fabric.dbc156f
	- tweakeroo 0.17.0
	- vmp 0.2.0+beta.7.93
	- xaerominimap 23.5.0
	- xaeroworldmap 1.30.6
	- yet_another_config_lib_v3 3.0.3+1.20
	   |-- com_twelvemonkeys_common_common-image 3.9.4
	   |-- com_twelvemonkeys_common_common-io 3.9.4
	   |-- com_twelvemonkeys_common_common-lang 3.9.4
	   |-- com_twelvemonkeys_imageio_imageio-core 3.9.4
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.9.4
	   \-- com_twelvemonkeys_imageio_imageio-webp 3.9.4
	- zoomify 2.10.0
	   |-- com_akuleshov7_ktoml-core-jvm 0.4.1
	   |-- dev_isxander_settxi_settxi-core 2.10.6
	   \-- dev_isxander_settxi_settxi-kotlinx-serialization 2.10.6
[17:27:55] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/D:/我的世界/原版mc/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[17:27:56] [main/INFO]: Compatibility level set to JAVA_17
[17:27:56] [main/INFO]: Loaded configuration file for Lithium: 115 options available, 1 override(s) found
[17:27:57] [main/ERROR]: Throwing
top.hendrixshen.magiclib.dependency.api.DepCheckException: Mod resolution encountered an incompatible mod set!
 Mod ommc-1_20_1 compat version check failed.
Requirements:
	Mod Fabric API (fabric) detected. Requires [>=0.84.0], but found 0.83.0+1.20!
	at top.hendrixshen.magiclib.util.FabricUtil.compatVersionCheck(FabricUtil.java:164) ~[magiclib-1_20_1-0.7.346+e235d92-stable-7bc0cb59101db32.jar:?]
	at top.hendrixshen.magiclib.dependency.impl.MagicMixinPlugin.onLoad(MagicMixinPlugin.java:45) ~[magiclib-1_20_1-0.7.346+e235d92-stable-7bc0cb59101db32.jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.onLoad(PluginHandle.java:119) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:709) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:498) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:460) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:488) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60) ~[?:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:53) ~[?:?]
[17:27:57] [main/ERROR]: A critical error occurred
top.hendrixshen.magiclib.dependency.api.DepCheckException: Mod resolution encountered an incompatible mod set!
 Mod ommc-1_20_1 compat version check failed.
Requirements:
	Mod Fabric API (fabric) detected. Requires [>=0.84.0], but found 0.83.0+1.20!
	at top.hendrixshen.magiclib.util.FabricUtil.compatVersionCheck(FabricUtil.java:164) ~[magiclib-1_20_1-0.7.346+e235d92-stable-7bc0cb59101db32.jar:?]
	at top.hendrixshen.magiclib.dependency.impl.MagicMixinPlugin.onLoad(MagicMixinPlugin.java:45) ~[magiclib-1_20_1-0.7.346+e235d92-stable-7bc0cb59101db32.jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.onLoad(PluginHandle.java:119) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:709) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:498) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:460) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:488) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60) ~[?:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:53) ~[?:?]
```

**Comment by Hendrix-Shen** [comment]
问题显而易见，更新fabric api。

**Comment by linyiyi1314** [comment]
ok

**Comment by linyiyi1314** [comment]
ok
