### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Adogs1** [Nyan-Work/oh-my-minecraft-client#45]
### Minecraft Version

1.21

### OMMC Version

按存储库构建

### Description

在作者的最新拉取请求中，经作者同意我克隆最新存储库，只按照要求更改了mod.version=0.5，其他未更改
随后编译的mod在我测试时进入ommc的配置页面崩溃
我的启动器PCL2报告说可能是MasaGadget-mc1.21-fabric-4.0.364-beta.jar或MagicLib 0.8.585 for Minecraft 1.21.0.jar导致崩溃

### To Reproduce

我编译的mod下载地址：https://wwi.lanzouq.com/iqqjk26t855g
使用1.21版本
在未进入游戏的主页面通过模组菜单mod（应该跟这个没关系）进入ommc的配置页面
等待或点击几个配置按键后崩溃

### Log

```
---- Minecraft Crash Report ----
// My bad.

Time: 2024-08-07 22:08:32
Description: Unexpected error

java.lang.NullPointerException: Cannot read field "field_1690" because "this.mc" is null
	at fi.dy.masa.malilib.event.InputEventHandler.onMouseScroll(InputEventHandler.java:211)
	at net.minecraft.class_312.handler$doa000$malilib$hookOnMouseScroll(class_312.java:1542)
	at net.minecraft.class_312.method_1598(class_312.java:140)
	at net.minecraft.class_312.method_22687(class_312.java:197)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_312.method_22685(class_312.java:197)
	at org.lwjgl.glfw.GLFWScrollCallbackI.callback(GLFWScrollCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:168)
	at net.minecraft.class_1041.method_15998(class_1041.java:303)
	at net.minecraft.class_310.method_1523(class_310.java:1307)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at fi.dy.masa.malilib.event.InputEventHandler.onMouseScroll(InputEventHandler.java:211)
	at net.minecraft.class_312.handler$doa000$malilib$hookOnMouseScroll(class_312.java:1542)
	at net.minecraft.class_312.method_1598(class_312.java:140)
	at net.minecraft.class_312.method_22687(class_312.java:197)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_312.method_22685(class_312.java:197)
	at org.lwjgl.glfw.GLFWScrollCallbackI.callback(GLFWScrollCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:168)

-- Uptime --
Details:
	JVM uptime: 38.687s
	Wall uptime: 25.134s
	High-res time: 19.317s
	Client ticks: 277 ticks / 13.850s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:905)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, appleskin, betterf3, caffeineconfig, carpet, carpet-extra, carpet-tis-addition, cloth-config, conditional-mixin, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fastchest, gca, inventoryhud, itemscroller, jade, kyrptconfig, litematica, lithium, magiclib, magiclib-1_21, magiclib_core, magiclib_malilib_extra, magiclib_minecraft_api, malilib, masa_gadget_mod, minihud, modmenu, ommc, pinyined-masa, quickshulker, reeses-sodium-options, sodium, sodium-extra, tweakermore, tweakeroo, xaerominimap, xaeroworldmap, file/护眼大补丸1.20-1.21 .zip, file/XKRD 红显v3.3for1.21.zip, file/XK Highlight Block.zip, file/Minecraft-Mod-Language-Modpack-Converted-1.21.zip

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 1508837376 bytes (1438 MiB) / 1929379840 bytes (1840 MiB) up to 5477761024 bytes (5224 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600G with Radeon Graphics         
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.89
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc.
	Graphics card #0 VRAM (MiB): 512.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.21912.14
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 19433.09
	Virtual memory used (MiB): 13166.07
	Swap memory total (MiB): 3712.00
	Swap memory used (MiB): 71.82
	Space in storage for jna.tmpdir (MiB): available: 100861.20, total: 307662.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 100861.20, total: 307662.00
	Space in storage for io.netty.native.workdir (MiB): available: 100861.20, total: 307662.00
	Space in storage for java.io.tmpdir (MiB): available: 72212.02, total: 168235.83
	Space in storage for workdir (MiB): available: 100861.20, total: 307662.00
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn783m -Xmx5222m
	Fabric Mods: 
		appleskin: AppleSkin 3.0.5+mc1.21
		betterf3: BetterF3 11.0.1
		carpet: Carpet Mod 1.4.147+v240613
		carpet-extra: Carpet Extra 1.4.147
		carpet-tis-addition: Carpet TIS Addition 1.61.1
			conditional-mixin: conditional mixin 0.6.2
			mixinextras: MixinExtras 0.3.6
		cloth-config: Cloth Config v15 15.0.128
			cloth-basic-math: cloth-basic-math 0.6.1
		fabric-api: Fabric API 0.100.8+1.21
			fabric-api-base: Fabric API Base 0.4.42+6573ed8cd1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.67+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bcd1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd9d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.15+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.18+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.4.2+c111832ad1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.25+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.13+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.10+e633f883d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.3+78017270d1
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a7d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.11+8f3583aed1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.13+3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.1+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.0+ab7edbacd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.13+d1321076d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.10+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.26+a5d66753d1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.3.0+0ae0b97dd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.6.5+48fb1586d1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd0d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.1+d153f344d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.2.0+7e687b32d1
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b5597344d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.83+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.15+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.12+6573ed8cd1
		fabricloader: Fabric Loader 0.15.11
		fastchest: FastChest 1.5+1.20.2
		gca: GugleCarpetAddition mc1.21-2.9.0+build.52
		i18nupdatemod: I18nUpdateMod 3.6.0-SNAPSHOT
		inventoryhud: Inventory HUD + 3.4.24
		itemscroller: Item Scroller 0.23.999-sakura.7
		jade: Jade 15.1.4+fabric
		java: OpenJDK 64-Bit Server VM 21
		litematica: Litematica 0.18.999-sakura.28
		lithium: Lithium 0.12.7
		magiclib: MagicLib 0.8.585+07e9d29-stable
			magiclib-1_21: MagicLib Legacy Compat for 1.21 0.8.24+ab878d3-stable
			magiclib_core: MagicLib Core API 0.8.116+ab878d3-stable
			magiclib_malilib_extra: MagicLib Malilib API 0.8.45+07e9d29-stable
			magiclib_minecraft_api: MagicLib Minecraft API 0.6.62+07e9d29-stable
		malilib: MaLiLib 0.20.2
		masa_gadget_mod: Masa Gadget 4.0.364+496ca1c-beta
		minecraft: Minecraft 1.21
		minihud: MiniHUD 0.31.999-sakura.19
		modmenu: Mod Menu 11.0.1
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		ommc: Oh My Minecraft Client 0.5.1+7d492db-dev
		pinyined-masa: pinyined-masa 0.6
		quickshulker: Quick Shulker 1.4.5-1.21
			kyrptconfig: Kyrpt Config 1.6.0-1.20.4
		reeses-sodium-options: Reese's Sodium Options 1.7.3+mc1.21
		sodium: Sodium 0.5.11+mc1.21
		sodium-extra: Sodium Extra 0.5.7+mc1.21
			caffeineconfig: CaffeineConfig 1.3.0+1.17
		tweakermore: TweakerMore 3.20.1
		tweakeroo: Tweakeroo 0.20.999-sakura.23
		xaerominimap: Xaero's Minimap 24.2.1
		xaeroworldmap: Xaero's World Map 1.38.8
	Launched Version: 1.21-Fabric 0.15.11
	Launcher name: PCL
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: AMD Radeon(TM) Graphics GL version 3.2.0 Core Profile Context 24.3.1.240216, ATI Technologies Inc.
	Window size: 873x508
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 12/12 chunks
	Resource Packs: vanilla, fabric, appleskin (incompatible), betterf3, caffeineconfig, carpet, carpet-extra, carpet-tis-addition, cloth-config, conditional-mixin, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fastchest, gca, inventoryhud, itemscroller, jade (incompatible), kyrptconfig, litematica, lithium, magiclib, magiclib-1_21, magiclib_core, magiclib_malilib_extra (incompatible), magiclib_minecraft_api (incompatible), malilib, masa_gadget_mod, minihud, modmenu, ommc, pinyined-masa, quickshulker, reeses-sodium-options, sodium, sodium-extra, tweakermore, tweakeroo (incompatible), xaerominimap (incompatible), xaeroworldmap (incompatible), file/护眼大补丸1.20-1.21 .zip, file/XKRD 红显v3.3for1.21.zip, file/XK Highlight Block.zip (incompatible), file/Minecraft-Mod-Language-Modpack-Converted-1.21.zip
	Current Language: zh_cn
	Locale: zh_CN
	System encoding: GBK
	File encoding: UTF-8
	CPU: 12x AMD Ryzen 5 5600G with Radeon Graphics 
```

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Adogs1** [comment]
现在，我带着该mod进入世界也会导致客户端崩溃，理由是注入失败

**Comment by Hendrix-Shen** [comment]
能否确认确实是由 OMMC 引起的问题？如果确认贴一下 latest.log，如果并非由 OMMC 引起，请向对应仓库报告问题

**Comment by Adogs1** [comment]
> 能否确认确实是由 OMMC 引起的问题？如果确认贴一下 latest.log，如果并非由 OMMC 引起，请向对应仓库报告问题

单独启用ommc及其前置并未发生崩溃，通过控制变量，我查到冲突的mod：Sodium钠。但我不确定是谁导致的崩溃

**Comment by Hendrix-Shen** [comment]
应该是世吞助手和模型无偏移那部分的问题，等着修吧

**Comment by Adogs1** [comment]
> 应该是世吞助手和模型无偏移那部分的问题，等着修吧

钠是我反复启用/禁止mod，进入世界导致崩溃的错误排查出来的。但这个issues最初的问题，在我启用全部mod，然后禁止钠及相关mod后，在配置文件逛的时候还是客户端崩溃了，报错与本issues提交的一样，我猜测这与进入世界导致客户端崩溃是两个不同的错误。不过我现在没空排查了......

**Comment by wendavid552** [comment]
> > 应该是世吞助手和模型无偏移那部分的问题，等着修吧
> 
> 钠是我反复启用/禁止mod，进入世界导致崩溃的错误排查出来的。但这个issues最初的问题，在我启用全部mod，然后禁止钠及相关mod后，在配置文件逛的时候还是客户端崩溃了，报错与本issues提交的一样，我猜测这与进入世界导致客户端崩溃是两个不同的错误。不过我现在没空排查了......

是的，另一个和锂有关，已经给两个bug提交了一个比较hacky的修复

**Comment by star-bailu** [comment]
你好，邮件已收到，谢谢

**Comment by Adogs1** [comment]
感谢，希望1.21正式版本能早点出来！！！

**Comment by ChenJL66666** [comment]
在0.6.361中似乎并未修复？我现在使用这个版本的ommc还是有这个问题
minecraft版本1.21.1，禁用锂之后仍然存在此问题
且保存存档的时候也会崩游戏！？？

**Comment by star-bailu** [comment]
你好，邮件已收到，谢谢
